#!/usr/bin/env bash

python -m inpainting_harmonization_test.test_ip_hm --name coco_inpainting_256_test_pair --gpu_ids 0 --ip_checkpoints_dir /home/eeb433/Documents/Yuhang/guided_inpainting/inpainting/log/coco_inpainting_256_dilation_2_exp1/20180214-223156 --harm_checkpoints_dir /home/eeb433/Dropbox/coco_inpainting_256_harm_all/20180217-033314 --loadSize 256 --fineSize 256 --label_nc 0 --dataroot /media/eeb433/Storage/Dataset/MSCOCO/val2017 --no_instance --resize_or_crop resize --tf_log --keep_hole_only --ann_path '/media/eeb433/Storage/Dataset/MSCOCO/annotations/instances_val2017.json' --how_many 4 --interpolated_conv --dilation 2


python -m inpainting_harmonization_test.test_ip_hm --name coco_inpainting_256_test_pair_with_seg --gpu_ids -1 --ip_checkpoints_dir /home/eeb433/Documents/Yuhang/guided_inpainting/inpainting/log/coco_inpainting_256_dilation_2_exp1/20180214-223156 --harm_checkpoints_dir /home/eeb433/Dropbox/coco_inpainting_256_harm_all/20180217-033314 --loadSize 256 --fineSize 256 --label_nc 0 --dataroot /media/eeb433/Storage/Dataset/MSCOCO/val2017 --no_instance --resize_or_crop resize --tf_log --keep_hole_only --ann_path '/media/eeb433/Storage/Dataset/MSCOCO/annotations/instances_val2017.json' --how_many 4 --interpolated_conv --dilation 2 --use_segmentation --seg_model_path '/home/eeb433/Documents/Yuhang/guided_inpainting/3rd_party/Mask_RCNN/log' --results_dir guided_inpainting_output

python -m inpainting_harmonization_test.test_ip_hm --name coco_inpainting_256_test_pair --gpu_ids 0 --ip_checkpoints_dir /home/harryyang/Dropbox/20180214-223156 --harm_checkpoints_dir /data/log/guided_inpainting/log_pix2pix_hd/coco_inpainting_256_harm_all/20180217-033314 --loadSize 256 --fineSize 256 --label_nc 0 --dataroot /data/public/MSCOCO/val2017 --no_instance --resize_or_crop resize --tf_log --keep_hole_only --ann_path '/data/public/MSCOCO/annotations/instances_val2017.json' --how_many 7 --interpolated_conv --dilation 2 --results_dir guided_inpainting_output

python -m inpainting_harmonization_test.test_ip_hm --name coco_inpainting_256_test_pair_with_seg --gpu_ids 0 --ip_checkpoints_dir /home/harryyang/Dropbox/20180214-223156 --harm_checkpoints_dir /data/log/guided_inpainting/log_pix2pix_hd/coco_inpainting_256_harm_all/20180217-033314 --loadSize 256 --fineSize 256 --label_nc 0 --dataroot /data/public/MSCOCO/val2017 --no_instance --resize_or_crop resize --tf_log --keep_hole_only --ann_path '/data/public/MSCOCO/annotations/instances_val2017.json' --how_many 7 --interpolated_conv --dilation 2 --use_segmentation --seg_model_path '/home/harryyang/Documents/guided_inpainting/third_party/Mask_RCNN' --results_dir guided_inpainting_output
